name: eventador
description: Persistence & Event Sourcing Extension for Dactor - Industrial-grade event sourcing platform with hybrid architecture
version: 1.0.0
repository: https://github.com/stephanfeb/eventador

environment:
  sdk: ^3.5.0

dependencies:
  # Event storage and serialization
  isar: ^3.1.0+1
  cbor: ^6.0.0
  meta: ^1.16.0  # Compatible with Flutter SDK version
  
  dactor: ^0.3.0
  duraq: ^0.0.1 

dev_dependencies:
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.7
  test: ^1.24.0
  mockito: ^5.4.2
  lints: ^5.0.0
